## Initial seed for categories table (static)
#Category.create!(name: "Marriage Documents")
#Category.create!(name: "Marriage Preparation Programs")
#Category.create!(name: "Proposals, Stags & Showers")
#Category.create!(name: "Chinese Engagement (Ting Hun)")
#Category.create!(name: "Church & Ceremony Venues")
#Category.create!(name: "Wedding Officiants")
#Category.create!(name: "Caterers")
#Category.create!(name: "Specialty Food Stations")
#Category.create!(name: "Gardens, Halls & Tent Venues")
#Category.create!(name: "Hotels")
#Category.create!(name: "Restaurants")
#Category.create!(name: "Wines & Spirits")
#Category.create!(name: "Photographers")
#Category.create!(name: "Engagement Stylist")
#Category.create!(name: "Album Suppliers")
#Category.create!(name: "Videographers")
#Category.create!(name: "Designers")
#Category.create!(name: "Barongs & Haberdasheries")
#Category.create!(name: "Accessories")
#Category.create!(name: "Undergarments")
#Category.create!(name: "Shoes")
#Category.create!(name: "Hair & Make Up")
#Category.create!(name: "Beauty, Spas & Fitness")
#Category.create!(name: "Coordinators / Wedding Planners")
#Category.create!(name: "Invitations")
#Category.create!(name: "Calligraphers")
#Category.create!(name: "Missaletter Makers")
#Category.create!(name: "Wax Seals")
#Category.create!(name: "Car Rentals & Limo Services")
#Category.create!(name: "Ring & Jewellers")
#Category.create!(name: "Gifts")
#Category.create!(name: "Onsite Souvenirs")
#Category.create!(name: "Charities & Causes")
#Category.create!(name: "Florists and Event Stylists")
#Category.create!(name: "Aircon Rentals")
#Category.create!(name: "Banquet Chairs")
#Category.create!(name: "Fireworks and Confetti")
#Category.create!(name: "Generator Set Rentals")
#Category.create!(name: "Lights & Sounds")
#Category.create!(name: "Tent Rentals")
#Category.create!(name: "LED Walls, Laptop & Projector")
#Category.create!(name: "Bands")
#Category.create!(name: "Choirs")
#Category.create!(name: "Custom-Made Songs")
#Category.create!(name: "Dance Classes & Chroreographers")
#Category.create!(name: "Emcees")
#Category.create!(name: "Soloist/Solo Instrumentalists")
#Category.create!(name: "Strings & Orchestra")
#Category.create!(name: "Talent Agencies")
#Category.create!(name: "Voice Coaches")
#Category.create!(name: "Airlines")
#Category.create!(name: "Cruises")
#Category.create!(name: "Resorts")
#Category.create!(name: "Travel Agencies")
#Category.create!(name: "Wedding Shops")
#Category.create!(name: "Post Wedding Services")
#Category.create!(name: "Workshop / Course for Wedding Planners")
#Category.create!(name: "Suppliers' Associations")
##initial seed for todo_items table (static)
#TodoItem.create!(item: "Budget")
#TodoItem.create!(item: "Marriage License")
#TodoItem.create!(item: "Ceremony Venue")
#TodoItem.create!(item: "Reception Venue")
#TodoItem.create!(item: "Ceremony Officiant")
#TodoItem.create!(item: "Wedding Planner or Coordinator")
#TodoItem.create!(item: "Photographer")
#TodoItem.create!(item: "Videographer")
#TodoItem.create!(item: "Catering")
#TodoItem.create!(item: "Bride's Attire")
#TodoItem.create!(item: "Hair and Make-up")
#TodoItem.create!(item: "Guest List")
#TodoItem.create!(item: "Entourage Line-up")
#TodoItem.create!(item: "Invitations")
#TodoItem.create!(item: "Wedding Registry")
#TodoItem.create!(item: "Wedding Rings")
#TodoItem.create!(item: "Wedding Preparation Venue/Hotel")
#TodoItem.create!(item: "Groom's Attire")
#TodoItem.create!(item: "Honeymoon Plans")
#TodoItem.create!(item: "Wedding Rings")
#TodoItem.create!(item: "Band or DJ")
#TodoItem.create!(item: "Photobooth")
#TodoItem.create!(item: "Flowers, Decors, and Styling")
#TodoItem.create!(item: "Lights and Sound")
#TodoItem.create!(item: "Wedding Program")
#initial seed for post_categories table (static)
PostCategory.create!(category: 1, post_type: 1, name: "Venues", description: "Forum - Venues")
PostCategory.create!(category: 1, post_type: 2, name: "Photo/Video", description: "Forum - Photo/Vid")
PostCategory.create!(category: 1, post_type: 3, name: "Food", description: "Forum - Food")
PostCategory.create!(category: 1, post_type: 4, name: "Music", description: "Forum - Music")
PostCategory.create!(category: 1, post_type: 5, name: "Attire and Accessories", description: "Forum - Attire/Accessories")
PostCategory.create!(category: 1, post_type: 6, name: "DIY Ideas", description: "Forum - DIY Ideas")
PostCategory.create!(category: 1, post_type: 7, name: "Pre-wedding Parties", description: "Forum - Pre-wedding Parties")
PostCategory.create!(category: 1, post_type: 8, name: "Counseling", description: "Forum - Counseling")


